version: '3.9'

services:

  web:
    image: nginx:latest
    ports:
      - '8765:80'
    domainname: microblog.localhost
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - .:/var/www

  composer:
    image: composer:2.5.5
    command: [ "composer", "install" ]
    volumes:
      - .:/app