<?php

namespace test\helper;

use helper\ApplicationConfig;
use PHPUnit_Framework_TestCase;

/**
 * Test class for Model.
 * Generated by PHPUnit on 2013-08-19 at 21:40:00.
 */
class ApplicationConfigTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ApplicationConfig
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ApplicationConfig("[foo]\nbar=baz", "[default]\ndefault = 1");
	}

	public function testAppEnv() {
		$this->assertFalse(defined('APP_ENV_FOO'));

		$this->object = new ApplicationConfig("[app_env]\nfoo = 1");

		$this->assertTrue(defined('APP_ENV_FOO'));
		$this->assertEquals(1, APP_ENV_FOO);
	}

	public function getSectionFromDefault() {
		$this->assertEquals(array('default' => '1'), $this->object->getSection('default'));
	}

	/**
	 * @test
	 */
	public function getSectionEntryFromDefault() {
		$this->object = new ApplicationConfig("[default]\nnodefault=2", "[default]\ndefault = 1");
		$this->assertEquals('1', $this->object->getSectionEntry('default', 'default'));
	}

	/**
	 * @test
	 */
	public function getSection() {
		$this->assertEquals(array('bar' => 'baz'), $this->object->getSection('foo'));
	}

	/**
	 * @test
	 */
	public function getSectionDefault() {
		$this->assertEquals(array('boo' => 'buff'), $this->object->getSection('fuzz', array('boo' => 'buff')));
	}

	/**
	 * @test
	 */
	public function getSectionEntry() {
		$this->assertEquals('baz', $this->object->getSectionEntry('foo', 'bar'));
	}

	/**
	 * @test
	 */
	public function getSectionEntryDefault() {
		$this->assertEquals('buzz', $this->object->getSectionEntry('foo', 'barr', 'buzz'));
	}
}
