<?php

namespace test\models;

use models\Model;
use PHPUnit_Framework_TestCase;

/**
 * Test class for Model.
 * Generated by PHPUnit on 2013-08-19 at 21:40:00.
 */
class ModelTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Model
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Model();
	}

	public function testIsValidNotValidated() {
		$this->assertFalse($this->object->isValid());
	}


	/**
	 * @todo Implement testGetValidationMessages().
	 */
	public function testGetValidationMessages() {
		$this->object->setId(1);
		$this->assertEmpty($this->object->getValidationMessages());
	}

	/**
	 * @todo Implement testIsValid().
	 */
	public function testIsValid() {
		$this->object->validate();
		$this->assertFalse($this->object->isValid());
		$this->assertEquals(array('id' => array('id must be numeric')), $this->object->getValidationMessages());
		$this->assertEquals(array('id must be numeric'), $this->object->getValidationMessages('id'));

		$this->object->setId(1);
		$this->object->validate();
		$this->assertTrue($this->object->isValid());
		$this->assertEquals(array(), $this->object->getValidationMessages());
		$this->assertEquals(array(), $this->object->getValidationMessages('id'));
	}

	/**
	 * @todo Implement testSetAttributes().
	 */
	public function testSetAttributes() {
		$this->object->setAttributes(array(
			'id' => 1
		));

		$this->assertEquals(1, $this->object->id);
	}

	public function testSetAttributesUponConstruct() {
		$model = new Model(array('id' => 17));
		$this->assertEquals(17, $model->id);
	}

	public function testSetGetId() {
		$this->object->setId(12);
		$this->assertEquals(12, $this->object->getId());
	}

}
