<?php

namespace test\helper;

use helper\ApplicationConfig;

/**
 * Test class for Model.
 * Generated by PHPUnit on 2013-08-19 at 21:40:00.
 */
class ApplicationConfigTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Model
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ApplicationConfig("[foo]\nbar=baz", '');
	}

	/**
	 * @test
	 */
	public function getSection() {
		$this->assertEquals(array('bar' => 'baz'), $this->object->getSection('foo'));
	}

	/**
	 * @test
	 */
	public function getSectionDefault() {
		$this->assertEquals(array('boo' => 'buff'), $this->object->getSection('fuzz', array('boo' => 'buff')));
	}

	/**
	 * @test
	 */
	public function getSectionEntry() {
		$this->assertEquals('baz', $this->object->getSectionEntry('foo', 'bar'));
	}

	/**
	 * @test
	 */
	public function getSectionEntryDefault() {
		$this->assertEquals('buzz', $this->object->getSectionEntry('foo', 'barr', 'buzz'));
	}

}
